import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';

// const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    favicon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.className}  bg-primary grid min-h-screen grid-cols-[auto_1fr] justify-center gap-4 overflow-hidden`}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
