export const mockDietVal = [
  'name',
  'calories',
  'serving_size_g',
  'fat_total_g',
  'fat_saturated_g',
  'protein_g',
  'sodium_mg',
  'potassium_mg',
  'cholesterol_mg',
  'carbohydrates_total_g',
  'fiber_g',
  'sugar_g',
];
export const mockDiet = {
  items: [
    {
      name: 'egg',
      calories: 73.5,
      serving_si: 32.3,
      ze_g: 50,
      fat_total_g: 4.8,
      fat_saturated_g: 1.6,
      protein_g: 6.3,
      sodium_mg: 69,
      potassium_mg: 99,
      cholesterol_mg: 185,
      carbohydrates_total_g: 0.4,
      fiber_g: 0,
      sugar_g: 0.2,
    },
    {
      name: 'bananas',
      calories: 206.3,
      serving_size_g: 236,
      fat_total_g: 0.8,
      fat_saturated_g: 0.3,
      protein_g: 2.6,
      sodium_mg: 2,
      potassium_mg: 52,
      cholesterol_mg: 0,
      carbohydrates_total_g: 52.9,
      fiber_g: 6.1,
      sugar_g: 28.7,
    },
  ],
};
